---
- name: Capture IBM Cloud POWERVS VSI
  hosts: localhost
  gather_facts: no
  collections:
    - ibm.cloudcollection

  vars_files:
    - vars.yaml

  tasks:
    - name: Get current date
      ansible.builtin.set_fact:
        current_date: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"

    - name: Set full image name with date
      ansible.builtin.set_fact:
        image_name: "{{ base_image_name }}_{{ current_date }}"

    - name: Capture POWERVS VSI to an image
      ibm.power_virtual_servers.powervs_image_capture:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        pi_image_name: "{{ image_name }}"
        pi_instance_name: "{{ vsi_name }}"
        pi_destination: "{{ destination_option }}"
        pi_volumes_to_exclude: "{{ volumes_name_to_exclude }}"
      register: capture_result

    - name: Display the capture result
      debug:
        msg: "{{ capture_result }}"
